### PR TITLE
Milestone 5 friendships v1

### PR DESCRIPTION
**Pull request by notrexxx**
**Create friendships model**

- A user can send a friendship invitation.
- A user can see a link to “Add as friend” next to other users names
- A user can see pending friendship invitations sent from other users
- A user can accept or reject friendships invitations
- A user can see a notice 'Friend' next to other users names when said user is his friend

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @notrexxx  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, this milestone is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all requirement so carefully, keep it up, and your project is really almost done.
:+1: Your codes look clean, keep up the good job!
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] When I click `Add as friend` to a given friend let's assume his name is Mark, when Mark logs in, he should see that I requested him a friendship, unfortunately it did not work like that, in contrast when Mark logged in, he was able to send me friend request, so kindly fix this issue.
- [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from Pathwright)
- [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from Pathwright)
- [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from Pathwright)
- [x] Improve on this Pull Request description, make it more descriptive

# [Optional changes] :yellow_circle: 
- [x] It would be nice if you display a signed in user in the navbar
- [ ] It would be very nice if you setup test on github actions in that way it will be very easy for everyone who visits your repo to know about tests status
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by notrexxx** [comment]
Hello @descholar-ceo

In my environment, I can send a friend request, see that is pending to be accepted, then go to the account of whom I sent the friend request and either accept it or reject it. When a friend is added, I can see him marked as a 'Friend' in the 'all users' tab.

**Comment by descholar-ceo** [comment]
> Hello @descholar-ceo
> 
> In my environment, I can send a friend request, see that is pending to be accepted, then go to the account of whom I sent the friend request and either accept it or reject it. When a friend is added, I can see him marked as a 'Friend' in the 'all users' tab.

Hello @notrexxx , thank you for reaching out for more clarification, I have just double checked and the issue is still there, maybe you can reset your database (`drop` and `create`) in order to have a fresh new db structure, just to make sure that the environment you have is the same as the one we have while reviewing. Once you got the issue, kindly fix it before requesting another review.

**Comment by notrexxx** [comment]
> > Hello @descholar-ceo
> > In my environment, I can send a friend request, see that is pending to be accepted, then go to the account of whom I sent the friend request and either accept it or reject it. When a friend is added, I can see him marked as a 'Friend' in the 'all users' tab.
> 
> Hello @notrexxx , thank you for reaching out for more clarification, I have just double checked and the issue is still there, maybe you can reset your database (`drop` and `create`) in order to have a fresh new db structure, just to make sure that the environment you have is the same as the one we have while reviewing. Once you got the issue, kindly fix it before requesting another review.


Hello @descholar-ceo 
I just dropped the database and created new users, everything is working as expected. I will drop it again and add a loom video.
https://www.loom.com/share/ca035f87175f422d9c88b65ad4852edd

**Comment by descholar-ceo** [comment]
> > > Hello @descholar-ceo
> > > In my environment, I can send a friend request, see that is pending to be accepted, then go to the account of whom I sent the friend request and either accept it or reject it. When a friend is added, I can see him marked as a 'Friend' in the 'all users' tab.
> > 
> > 
> > Hello @notrexxx , thank you for reaching out for more clarification, I have just double checked and the issue is still there, maybe you can reset your database (`drop` and `create`) in order to have a fresh new db structure, just to make sure that the environment you have is the same as the one we have while reviewing. Once you got the issue, kindly fix it before requesting another review.
> 
> Hello @descholar-ceo
> I just dropped the database and created new users, everything is working as expected. I will drop it again and add a loom video.
> 
> https://www.loom.com/share/ca035f87175f422d9c88b65ad4852edd

Ooh! I got you now! And I can see that's how it works, but the `Accept` and `Reject` buttons should appear next to the name of that friend who requested in the users list. 

See, when you click on `ALL USERS`, you will find that even those who sent you friend requests have this button `Add as a friend` button, which is wrong, it should be `Accept` or `Reject` buttons
Screenshot from 2021-05-07 10-11-32

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @notrexxx 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes by the previous code reviewer  👇.
- [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png)  from Pathwright)
- [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png)  from Pathwright)
- [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from Pathwright)

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by notrexxx** [comment]
The user can accept or reject any pending friendships on his user profile. It is not specified where the user must do such action.

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 👯 

Hello there @notrexxx 👋🏾 👋🏾 , great job on working on the requested changes, I watched your video and I understood where your accept and reject buttons were called from. Your linters are not performing any errors.  Great job 😄 

#### OPTIONAL 🟢 

- Although it's not specified where a user can accept and reject requests from, it would be nice to give a user a better experience in your app if they just accepted the requests from all user's link, don't you think so? 😄 (Purely optional)

With that, I approve of this project, go ahead and merge. All the best in the next milestones.

Regards
Peris Ndanu

**Pull request merged**
